import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { builder, BuilderComponent } from "@builder.io/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

builder.init(process.env.NEXT_PUBLIC_BUILDER_PUBLIC_API_KEY || "");

export async function getServerSideProps() {
  const template =
    (await builder
      .get("navigation-links-test", { options: { enrich: true } })
      .toPromise()) || null;

  return { props: { template } };
}

export default function Home({ template }: any) {
  const [openModal, setOpenModal] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div
            className={styles.modal}
            onMouseOver={() => setOpenModal(true)}
            onMouseLeave={() => setOpenModal(false)}
          >
            <div
              className={styles.modal}
              style={{ display: openModal ? "block" : "none" }}
            >
              <h1>Modal Title</h1>
              <BuilderComponent
                model="navigation-links-test"
                content={template}
                options={{ enrich: true }}
              />
            </div>
            <button>Open Modal</button>
          </div>
        </main>
      </div>
    </>
  );
}
